### ISSUE TITLE
Running Tests

### ISSUE THREAD

**Issue by BernardDuffin** [neslib/Neslib.Xml#10]
Compiled in 32 and 64 and get the same results
Delphi 11 Version 28.0.44500.8973 

XML Performance Tests (64-bits)
Select XML library:
  0. Delphi (Default)
  1. MSXML
  2. OmniXML
  3. VerySimpleXml
  4. SimpleXML
  5. Alcinoe
  6. Neslib (Unicode mode)

Enter library number: 6
Running test...

Memory usage : 44744 KB
Load time    : 250.72 ms
ERROR: Invalid number of attributes (expected=56317, actual=56310)
Traverse time: 31.38 ms
Query time   : 1.52 ms
Destroy time : 33.94 ms

Finished!

**Comment by neslib** [comment]
Good catch. This issue was introduced when I merged PR #5. That resulted in empty attributes being skipped.
This is fixed now.

**Comment by BernardDuffin** [comment]
Thanks for the quick fix 👍
