### ISSUE TITLE
A bit strange code

### ISSUE THREAD

**Issue by Alekcvp** [neslib/Neslib.Xml#3]
I have some doubts that this code does exactly what it should:
```
function TXmlDocument.GetDocumentElement: TXmlNode;
begin
  if (FRoot <> nil) then
  begin
    Result := FRoot.FirstChild;
    while (Result <> nil) do
    begin
      if (Result.NodeType = TXmlNodeType.Element) then
        Exit;
    end;
  end;
  Result.FNode := nil;
end;
```
Especially the part of it that is inside the while-loop...

**Comment by neslib** [comment]
Oops. You are right. I forgot to update Result to the next sibling inside the loop. Just pushed a fix for that.
Thanks for pointing this out!
